apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8deploy
  labels:
    app: web3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web3
      strategy:
       type: RollingUpdate
  template:
    metadata:
      labels:
        app: web3
    spec:
      containers:
        - name: backend
          image: worldchanger/kubedemo
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
 
       