apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8deploy
  labels:
    app: web3
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels :
      app: web3
  template:
    metadata:
      labels:
        app: web3
    spec:
      containers:
        - name: backend
          image: worldchanger/kubedemo:${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
 
       