apiVersion: v1
kind: Service
metadata:
  name: servicedemo 
  labels:
    app: web3
spec:
  ports:
  - nodePort: 30500
    port: 90
    protocol: TCP
    targetPort: 90
  selector:
    app: web3
  type: NodePortee